# --- atmega328p on breadboard
BOARD_TAG    = arduino 
ISP_PROG     = usbasp
AVRDUDE_OPTS = -v
AVRDUDE_ARD_BAUDRATE = 57600
AVRDUDE_ARD_PROGRAMMER = arduino 
BOARDS_TXT   = /usr/share/arduino/hardware/arduino/boards.txt
MCU = atmega328p
F_CPU = 16000000UL
MONITOR_PORT = /dev/ttyUSB0
ARDUINO_VAR_PATH = /usr/share/arduino/hardware/arduino/variants
include /home/pi/Arduino-Makefile-master/Arduino.mk
